language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - git clone https://github.com/alanxz/rabbitmq-c rabbitmq-c
  - cd rabbitmq-c
  - git checkout v0.5.1
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
  - cd ..
  - pecl install amqp
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/clover.xml
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php build/coverage-checker.php build/clover.xml 70; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.3' ]; then ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/; fi"

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
