language: php

sudo: required

services:
  - docker

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - PHP_AMQP_VERSION=v1.7.0 LIBRABBITMQ_VERSION=v0.8.0
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - sh build/install_deps.sh
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # update composer and fetch dependencies
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/clover.xml
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php build/coverage-checker.php build/clover.xml 70; fi"
  - sh -c "./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/"

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
