language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
- LIBRABBITMQ_VERSION=v0.5.1 PHP_AMQP_VERSION=v1.4.0

before_script:
  # install librabbitmq C library (required by php-amqp)
  - sh -c "git clone git://github.com/alanxz/rabbitmq-c.git"
  - sh -c "cd rabbitmq-c && git checkout ${LIBRABBITMQ_VERSION}"
  - sh -c "cd rabbitmq-c && cmake -DBUILD_EXAMPLES=No -DBUILD_TOOLS=No -DBUILD_TESTS=No ."
  - sh -c "cd rabbitmq-c && make && sudo make install"
  # install php-amqp extension
  - sh -c "git clone git://github.com/pdezwart/php-amqp.git"
  - sh -c "cd php-amqp && git checkout ${PHP_AMQP_VERSION}"
  - sh -c "cd php-amqp && phpize && ./configure && make && sudo make install"
  # add amqp extension to php.ini
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # get PSR-0 autoloader
  - sh -c "curl -s http://getcomposer.org/installer | php --"
  - sh -c "php composer.phar --dev install"
  - sh -c "php -i"
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/clover.xml
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php build/coverage-checker.php build/clover.xml 70; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.3' ]; then ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/; fi"

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
